# Assignment 2 

In [1]:
import numpy as np
import pandas as pd

In [7]:
v1 = np.array([1, 6, 7, 9])
v2 = np.array([1, 0, 6, 9])
result = np.sum(v1 == v2)
print(result)

2


In [25]:
matrix = np.random.randint(0, 100, (10, 3))
print(f'The shape of the matrix is {matrix.shape}')
print(f'The number of rows of the matrix is {matrix.shape[0]}')
print(f'The number of columns of the matrix us {matrix.shape[1]}')

print(f'\nThe matrix before modification\n {matrix}')

j = 0
for i in range(0, matrix.shape[0]):
    result = matrix[i][j] + matrix[i][j+1]
    if(result % 4 == 0):
        matrix[i][j+2] = 1
    else: 
        matrix[i][j+2] = 0
print(f'\nMatrix after evaluation\n {matrix}')

The shape of the matrix is (10, 3)
The number of rows of the matrix is 10
The number of columns of the matrix us 3

The matrix before modification
 [[ 1 36 70]
 [61 81 38]
 [88 98 69]
 [82 78 87]
 [50 21 39]
 [89 84 93]
 [15 56 73]
 [59 64 59]
 [41 73 68]
 [40 37 71]]

Matrix after evaluation
 [[ 1 36  0]
 [61 81  0]
 [88 98  0]
 [82 78  1]
 [50 21  0]
 [89 84  0]
 [15 56  0]
 [59 64  0]
 [41 73  0]
 [40 37  0]]


In [ ]:
colunmns = []
df = pd.DataFrame()